### ISSUE TITLE
Release source tarballs are incomplete

### ISSUE THREAD

**Issue by 4re** [sekrit-twc/timecube#1]
The release source tarball's `vsxx` directory is empty. This makes Linux packages such as Gentoo ones hard to deploy.

**Comment by sekrit-twc** [comment]
vsxx is a submodule. There are no "release source tarballs", other than what GitHub generates automatically.

**Comment by 4re** [comment]
Can you then please make a release for `vsxx`? That would help a bunch for packaging.

**Comment by sekrit-twc** [comment]
Unfortunately, this is just the way that GitHub works. You'll have to clone the repo with git.

e.g. https://github.com/supercollider/supercollider/issues/1807

**Comment by 4re** [comment]
Sorry, English is not my forte and I posted in the wrong issue in fact.
I meant a proper release for the `vsxx` package, like `vsxx-1.0.0` or whatever, so that way I could pull a numbered release in `timecube`'s package from `vsxx` package.
Right now `vsxx` is lacking any release. Yes, this is a request for `vsxx`, sorry for the confusion.

**Comment by sekrit-twc** [comment]
Unfortunately, that is not how development with submodules works. The required version of the submodule is tracked in Git, which you can see from the browser as "vsxx @ 6e48956" at the current master.
